- name: Install qemu-guest-agent on Debian/Ubuntu
  apt:
    name: qemu-guest-agent
    state: present
  when: ansible_os_family == "Debian"

- name: Install qemu-guest-agent on RedHat/CentOS
  yum:
    name: qemu-guest-agent
    state: present
  when: ansible_os_family == "RedHat"